server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.2.188:3306/rbac_seurity?ssl=fasle
    url: jdbc:mysql://120.79.197.130:3307/test?ssl=fasle
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.security.model
  configuration:
    mapUnderscoreToCamelCase: true


logging:
  level:
    org.springframework.web: INFO
    com.example.seurity.mapper: DEBUG